// Shopping List Items
export const GET_ITEMS_LIST="GET_ITEMS_LIST";
export const ADD_ITEM_LIST="ADD_ITEM_LIST";
export const DELETE_ITEM_LIST="DELETE_ITEM_LIST";
export const CHECK_ITEM_LIST="CHECK_ITEM_LIST";
export const SET_NAME_LIST="SET_NAME_LIST";
export const LIST_STATUS_LIST="LIST_STATUS_LIST";
export const DECR_ITEM_LIST="DECR_ITEM_LIST";
export const MODAL_STATE="MODAL_STATE";
export const OVERVIEW_STATE="OVERVIEW_STATE";
export const ISMOBILE="ISMOBILE";

// Main Items 

export const GET_ITEMS_MAIN="GET_ITEMS_MAIN";


//BOTH LOADING AND UNLOADING
export const LOADING="LOADING";